cluster = "devnet"
# wallet = "usb://ledger?key=0"
wallet = "~/.config/solana/id.json"
program-id = "JPEngBKGXmLUWAXrqZ66zTUzXNBirh5Lkjpjh7dfbXV"
#multisig = "3MmkfR292hdJjGv8uwC5LHS7EgsQHySgMCmjje6VPp4W"
multisig = "Gh9hZPvaub228asATx5auHxQbkAqzqrTZwS4X2FFhSjF"