[package]
name = "jet-multisig-cli"
version = "0.1.0"
edition = "2018"


[dependencies]
jet-multisig-client = { path = "../client" }
multisig-client = { path = "../../client" }
multisig-cli = { path = "../../cli" }
